### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ZzamZ** [Uraneptus/Sullys-Mod#108]
[message.txt](https://github.com/user-attachments/files/18137236/message.txt)
Crash Report of the mod crashing on servers!

**Comment by Uraneptus** [comment]
Will look into this soon

**Comment by McPersson** [comment]
Encountered a similar issue. The server crashes during startup due to Sully's Mod (sullysmod-3.2.0-beta) attempting to load a client-side class (HumanoidModel) on the server. This occurs in the initialization phase and results in an IllegalStateException caused by RuntimeDistCleaner detecting an invalid environment (DEDICATED_SERVER).

```
java.lang.IllegalStateException: Attempted to load class net.minecraft.client.model.HumanoidModel for invalid dist DEDICATED_SERVER
  at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
  at net.minecraftforge.fml.loading.RuntimeDistCleaner.transform(RuntimeDistCleaner.java:44)
  ...
```

**Comment by Uraneptus** [comment]
that's the same issue ye!

**Comment by Uraneptus** [comment]
fixed. Will release an update soon
