### ISSUE TITLE
[1.20.1] Crash on server startup with the newest version 3.1.0

### ISSUE THREAD

**Issue by BugmanBugman** [Uraneptus/Sullys-Mod#79]
https://gist.github.com/BugmanBugman/8e41e3ec2ceda4de00675074c929a455

**Comment by Uraneptus** [comment]
Please send your latest.log as well!

**Comment by BugmanBugman** [comment]
My latest: https://gist.github.com/BugmanBugman/cfad694e0b3fed49d1ebc12d975e0ca2

**Comment by Uraneptus** [comment]
Since I was not able to replicate this issue, I have to send you a file with a possible fix.
[sullysmod-3.1.0-beta.zip](https://github.com/Uraneptus/Sullys-Mod/files/13740805/sullysmod-3.1.0-beta.zip)
This zip file includes a mod file, that hopefully fixes your issue. Please test it. If it does not fix the issue, send me your log again!

**Comment by BugmanBugman** [comment]
Still getting it :(
https://gist.github.com/BugmanBugman/552f51d23042baf70181c4d89ac0ece0

**Comment by Uraneptus** [comment]
Okay thank you! I'll try something else

**Comment by Uraneptus** [comment]
Please try this file:
[sullysmod-3.1.0-beta.zip](https://github.com/Uraneptus/Sullys-Mod/files/13746295/sullysmod-3.1.0-beta.zip)

**Comment by BugmanBugman** [comment]
Yes! This works

**Comment by Uraneptus** [comment]
Awesome! Thanks for testing it ^^
